---
- include_vars:
     file: vars/docker_repositories.yml

- name: Agregamos la llave GPG a OS DEBIAN para disponer el repositorio Docker
  apt_key:
    url: '{{debian_repos.gpg}}'
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Debian" 



- name: Agregamos el repositorio A OS DEBIAN al Source list 
  apt_repository:
    repo: "{{debian_repos.r}} {{ansible_facts['lsb'].codename}} stable"   
    state: present
  when: ansible_facts['os_family'] == "Debian" 